FROM centos

RUN yum install -y \
   java-1.8.0-openjdk \
   java-1.8.0-openjdk-devel

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk/



RUN mkdir WORKDIR /usr/local/tomcat

WORKDIR /usr/local/tomcat
RUN curl -O https://www-eu.apache.org/dist/tomcat/tomcat-9/v9.0.27/bin/apache-tomcat-9.0.27.tar.gz
RUN tar xvfz apache*.tar.gz
RUN mv apache-tomcat-9.0.27/* /usr/local/tomcat/.
RUN yum -y install java
RUN java -version

COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
COPY context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml
VOLUME ["tomcat-dir", "/usr/local/tomcat/"]
EXPOSE 8080

CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]